JuriScan - Sistema di Ricerca Documentale: SearchEngine.Pylucene Namespace Reference
SearchEngine.Pylucene Namespace Reference
Functions
def initialize_jvm ()
Initialize the Java Virtual Machine for PyLucene.
def calculate_precision_recall (searcher, query_string, ranking_type="BM25", threshold=0.5)
Calculate precision and recall metrics for a given query.
def search_documents (searcher, title_true, abstract_true, corpus_true, query_string, ranking_type)
Main search function for PyLucene engine.
def get_wordnet_pos (tag)
Map NLTK POS tags to WordNet POS tags for lemmatization.
def expand_query (query_string)
Expand natural language query using NLP techniques.
def index_exists (index_path)
Check if a valid Lucene index exists at the specified path.
def create_index ()
Create or open PyLucene index for document searching.
Variables
project_root = Path(__file__).parent.parent
json_file = str(project_root / "WebScraping/results/Docs_cleaned.json")
index_file = str(project_root / "SearchEngine/index")
Function Documentation
calculate_precision_recall()
def SearchEngine.Pylucene.calculate_precision_recall (searcher, query_string, ranking_type = "BM25", threshold = 0.5)
Calculate precision and recall metrics for a given query.
Parameters
searcher The Lucene IndexSearcher object
query_string The search query string
ranking_type Ranking algorithm to use ("BM25" or "Classic")
threshold Score threshold for relevance determination (default: 0.5)
Returns
Tuple containing (precision_values, recall_values, normalized_scores)
Executes search across all fields and calculates precision-recall metrics using adaptive threshold based on score distribution
Definition at line 62 of file Pylucene.py.
References SearchEngine.Pylucene.expand_query().
Referenced by SearchEngine.Pylucene.search_documents().
create_index()
def SearchEngine.Pylucene.create_index ()
Create or open PyLucene index for document searching.
Returns
Tuple containing (directory, searcher) objects
Creates new index if none exists, otherwise opens existing index. Processes documents from JSON file using incremental parsing for memory efficiency.
Exceptions
Exception if indexing fails or JVM initialization problems occur
Definition at line 369 of file Pylucene.py.
References SearchEngine.Pylucene.create_index(), SearchEngine.Pylucene.index_exists(), and SearchEngine.Pylucene.initialize_jvm().
Referenced by SearchEngine.Pylucene.create_index().
expand_query()
def SearchEngine.Pylucene.expand_query (query_string)
Expand natural language query using NLP techniques.
Parameters
query_string The natural language query to expand
Returns
Expanded query string formatted for Lucene
Uses YAKE for keyword extraction, NLTK for NLP processing, and WordNet for semantic expansion with synonyms, hypernyms, and hyponyms
Definition at line 256 of file Pylucene.py.
References SearchEngine.Pylucene.get_wordnet_pos().
Referenced by SearchEngine.Pylucene.calculate_precision_recall(), and SearchEngine.Pylucene.search_documents().
get_wordnet_pos()
def SearchEngine.Pylucene.get_wordnet_pos (tag)
Map NLTK POS tags to WordNet POS tags for lemmatization.
Parameters
tag NLTK POS tag string
Returns
WordNet POS tag constant
Converts NLTK part-of-speech tags to WordNet format for accurate lemmatization
Definition at line 241 of file Pylucene.py.
Referenced by SearchEngine.Pylucene.expand_query().
index_exists()
def SearchEngine.Pylucene.index_exists (index_path)
Check if a valid Lucene index exists at the specified path.
Parameters
index_path Path to the index directory
Returns
True if valid index exists, False otherwise
Verifies both directory existence and index validity using DirectoryReader
Definition at line 356 of file Pylucene.py.
Referenced by SearchEngine.Pylucene.create_index().
initialize_jvm()
def SearchEngine.Pylucene.initialize_jvm ()
Initialize the Java Virtual Machine for PyLucene.
Sets up the JVM with headless configuration for server environments. Attaches the current thread to the JVM if it's already initialized.
Returns
None
Exceptions
Exception if JVM initialization fails
Definition at line 48 of file Pylucene.py.
Referenced by SearchEngine.Pylucene.create_index().
search_documents()
def SearchEngine.Pylucene.search_documents (searcher, title_true, abstract_true, corpus_true, query_string, ranking_type)
Main search function for PyLucene engine.
Parameters
searcher The Lucene IndexSearcher object
title_true Boolean flag to search in title field
abstract_true Boolean flag to search in abstract field
corpus_true Boolean flag to search in corpus field
query_string The search query string
ranking_type Ranking algorithm to use ("BM25" or "TFIDF")
Returns
Tuple containing (results, precision_recall_data, plot_path)
Supports both field-specific and checkbox-based searches with logical operators (AND/OR) across all fields. Includes precision-recall analysis.
Definition at line 182 of file Pylucene.py.
References SearchEngine.Pylucene.calculate_precision_recall(), and SearchEngine.Pylucene.expand_query().
Referenced by WebApp.PyLuceneUI.searchUI(), and WebApp.WhooshUI.searchUI().
Variable Documentation
index_file
SearchEngine.Pylucene.index_file = str(project_root / "SearchEngine/index")
Definition at line 25 of file Pylucene.py.
json_file
SearchEngine.Pylucene.json_file = str(project_root / "WebScraping/results/Docs_cleaned.json")
Definition at line 24 of file Pylucene.py.
project_root
SearchEngine.Pylucene.project_root = Path(__file__).parent.parent
Definition at line 23 of file Pylucene.py.