JuriScan - Sistema di Ricerca Documentale: WebScraping.results.CleanDocuments Namespace Reference
WebScraping.results.CleanDocuments Namespace Reference
Functions
def clean_mathematical_text (text)
Clean text containing mathematical expressions and Unicode artifacts.
def remove_control_characters (text)
Remove invalid control characters from text.
def clean_documents_in_batches (input_path, output_path="WebScraping/results/Docs_cleaned.json", batch_size=1000)
Process and clean documents in memory-efficient batches.
Variables
string input_path = "WebScraping/results/Docs.json"
string output_path = "WebScraping/results/Docs_cleaned.json"
Function Documentation
clean_documents_in_batches()
def WebScraping.results.CleanDocuments.clean_documents_in_batches (input_path, output_path = "WebScraping/results/Docs_cleaned.json", batch_size = 1000)
Process and clean documents in memory-efficient batches.
Parameters
input_path Path to the input JSON file with raw documents
output_path Path to the output JSON file for cleaned documents
batch_size Number of documents to process in each batch (default: 1000)
Implements incremental JSON parsing and batch processing for large datasets. Provides progress tracking and error handling for robust document cleaning.
Returns
None
Exceptions
FileNotFoundError if input file doesn't exist
OSError for file I/O errors
Definition at line 110 of file CleanDocuments.py.
References WebScraping.results.CleanDocuments.clean_documents_in_batches(), WebScraping.results.CleanDocuments.clean_mathematical_text(), and WebScraping.results.CleanDocuments.remove_control_characters().
Referenced by WebScraping.results.CleanDocuments.clean_documents_in_batches(), and Scraper.init().
clean_mathematical_text()
def WebScraping.results.CleanDocuments.clean_mathematical_text (text)
Clean text containing mathematical expressions and Unicode artifacts.
Parameters
text Input text with mathematical notation and Unicode characters
Returns
Cleaned text with mathematical expressions normalized
Removes specific Unicode characters, LaTeX artifacts, HTML conversion errors, and mathematical notation while preserving readable content
Definition at line 23 of file CleanDocuments.py.
Referenced by WebScraping.results.CleanDocuments.clean_documents_in_batches().
remove_control_characters()
def WebScraping.results.CleanDocuments.remove_control_characters (text)
Remove invalid control characters from text.
Parameters
text Input text potentially containing control characters
Returns
Text with control characters removed
Removes ASCII control characters (0x00-0x1F and 0x7F) that can cause issues in text processing and database storage
Definition at line 96 of file CleanDocuments.py.
Referenced by WebScraping.results.CleanDocuments.clean_documents_in_batches().
Variable Documentation
input_path
string WebScraping.results.CleanDocuments.input_path = "WebScraping/results/Docs.json"
Definition at line 17 of file CleanDocuments.py.
output_path
string WebScraping.results.CleanDocuments.output_path = "WebScraping/results/Docs_cleaned.json"
Definition at line 21 of file CleanDocuments.py.