JuriScan - Sistema di Ricerca Documentale: WebApp.PyLuceneUI Namespace Reference
WebApp.PyLuceneUI Namespace Reference
Functions
def searchUI ()
Main Streamlit UI function for PyLucene search interface.
Variables
project_root = Path(__file__).parent.parent
json_file = str(project_root / "WebScraping/results/Docs_cleaned.json")
directory
searcher
Function Documentation
searchUI()
def WebApp.PyLuceneUI.searchUI ()
Main Streamlit UI function for PyLucene search interface.
Creates complete web interface including:
JVM initialization and index management
Search field configuration and filters
Document ranking type selection (TF_IDF, BM25)
Results display with document scores and links
Integration with PyLucene precision-recall metrics
Returns
None
Definition at line 27 of file PyLuceneUI.py.
References SearchEngine.Pylucene.search_documents(), and WebApp.PyLuceneUI.searchUI().
Referenced by WebApp.PyLuceneUI.searchUI().
Variable Documentation
directory
WebApp.PyLuceneUI.directory
Definition at line 25 of file PyLuceneUI.py.
json_file
WebApp.PyLuceneUI.json_file = str(project_root / "WebScraping/results/Docs_cleaned.json")
Definition at line 20 of file PyLuceneUI.py.
project_root
WebApp.PyLuceneUI.project_root = Path(__file__).parent.parent
Definition at line 19 of file PyLuceneUI.py.
searcher
WebApp.PyLuceneUI.searcher
Definition at line 25 of file PyLuceneUI.py.